package handlers

import (
	"encoding/json"
	"errors"
	"net/http"
	"regexp"
	"strings"
)

// maxBodySize is the default maximum request body size (1 MB).
const maxBodySize int64 = 1 << 20

// WriteJSON writes a JSON response with the given status code.
func WriteJSON(w http.ResponseWriter, status int, data interface{}) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	json.NewEncoder(w).Encode(data)
}

// WriteError writes a JSON error response. Uses json.Marshal to prevent injection
// (fixes VALID-01 -- no more string concatenation with err.Error()).
func WriteError(w http.ResponseWriter, status int, code string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	json.NewEncoder(w).Encode(map[string]string{"error": code})
}

// DecodeJSON reads and decodes a JSON request body with size limit and Content-Type check.
// Returns false if decoding failed (error already written to w).
// Addresses VALID-02 (body size limits) and VALID-07 (Content-Type enforcement).
func DecodeJSON(w http.ResponseWriter, r *http.Request, maxBytes int64, dst interface{}) bool {
	// Check Content-Type — only enforce when header is present (VALID-07)
	ct := r.Header.Get("Content-Type")
	if ct != "" && !strings.HasPrefix(ct, "application/json") {
		WriteError(w, http.StatusUnsupportedMediaType, "content_type_must_be_json")
		return false
	}
	// Limit body size (VALID-02)
	r.Body = http.MaxBytesReader(w, r.Body, maxBytes)
	if err := json.NewDecoder(r.Body).Decode(dst); err != nil {
		var maxBytesErr *http.MaxBytesError
		if errors.As(err, &maxBytesErr) {
			WriteError(w, http.StatusRequestEntityTooLarge, "request_too_large")
		} else {
			WriteError(w, http.StatusBadRequest, "invalid_request")
		}
		return false
	}
	return true
}

// prefixedUUIDPattern matches IDs in the format "prefix_<uuid>" (e.g., "rec_550e8400-...").
var prefixedUUIDPattern = regexp.MustCompile(`^[a-z]{2,5}_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`)

// hashIDPattern matches IDs in the format "item_<hex>" generated by FNV hashing (e.g., "item_a1b2c3d4e5f6g7h8").
var hashIDPattern = regexp.MustCompile(`^item_[0-9a-f]{1,16}$`)

// ValidateID checks that a path/query parameter ID is non-empty and matches the
// prefixed UUID format used in this codebase (e.g., "rec_550e8400-e29b-...").
// Returns false if validation failed (error already written to w). Addresses VALID-04.
func ValidateID(w http.ResponseWriter, id, paramName string) bool {
	if id == "" {
		WriteError(w, http.StatusBadRequest, paramName+"_required")
		return false
	}
	if !prefixedUUIDPattern.MatchString(id) {
		WriteError(w, http.StatusBadRequest, "invalid_"+paramName)
		return false
	}
	return true
}

// ValidateItemID checks that a shopping item ID is non-empty and matches either
// the hash-based format (e.g., "item_a1b2c3d4") or custom item UUID format (e.g., "citem_550e8400-...").
func ValidateItemID(w http.ResponseWriter, id, paramName string) bool {
	if id == "" {
		WriteError(w, http.StatusBadRequest, paramName+"_required")
		return false
	}
	if !hashIDPattern.MatchString(id) && !prefixedUUIDPattern.MatchString(id) {
		WriteError(w, http.StatusBadRequest, "invalid_"+paramName)
		return false
	}
	return true
}
